### ISSUE TITLE
armv7 crashes from time to time

### ISSUE THREAD

**Issue by svillar** [ronhks/panasonic-aquarea-smart-cloud-mqtt#5]
This is the most I could get
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2795bc]

goroutine 1 [running]:
github.com/ronhks/panasonic-aquarea-smart-cloud-mqtt/src/data.GetDeviceData()
        /Users/ronhks/dev/src/git/github/ronhks/panasonic-aquarea-smart-cloud-mqtt/src/data/data.go:109 +0x124
main.getStatusData()
        /Users/ronhks/dev/src/git/github/ronhks/panasonic-aquarea-smart-cloud-mqtt/main.go:67 +0x2c
main.startQueryStatusData()
        /Users/ronhks/dev/src/git/github/ronhks/panasonic-aquarea-smart-cloud-mqtt/main.go:30 +0x24
main.startQueryStatusData()
        /Users/ronhks/dev/src/git/github/ronhks/panasonic-aquarea-smart-cloud-mqtt/main.go:40 +0xe8
main.main()
        /Users/ronhks/dev/src/git/github/ronhks/panasonic-aquarea-smart-cloud-mqtt/main.go:24 +0xd0
```

**Comment by ronhks** [comment]
Ohh, I will check it. Actually I have a huge load.

**Comment by ronhks** [comment]
Meanwhil beacuse this is a critial(Blocker) issue, I put error handling.

I created a new image (arm64):
https://hub.docker.com/repository/docker/ronhks/panasonic-aquarea-smart-cloud-mqtt

**Comment by svillar** [comment]
The problem is that now the image does not boot properly as I get a sequence of 
```
INFO[0002] Login success                                
ERRO[0005] Empty response from Energy Conspumption API  
ERRO[0005] Error while get DeviceData     
```

**Comment by ronhks** [comment]
Hi Guys!

I fixed the problem. Sorry for inconveniences and thanks for your patience!

The new version available on dockerhub:
https://hub.docker.com/repository/registry-1.docker.io/ronhks/panasonic-aquarea-smart-cloud-mqtt/general
